
[firebase]
apiKey     = "REPLACE_IN_STREAMLIT"
authDomain = "flag-playmaker.firebaseapp.com"
projectId  = "flag-playmaker"
databaseURL= ""
storageBucket = ""

[openai]        # optional
key = "REPLACE_IN_STREAMLIT"